<?php

/**
 * @todo admin interface to activate and enter path to the critical path css file / warn if file not exists
 * @todo check if cache module is configured
 */

/**
 * Implements hook_boot().
 */
function critical_path_css_boot() {
  // After first load CSS files should already be cached
  if (_critical_path_css_is_active() && !isset($_COOKIE['critical_path_css_cached'])) {
    setcookie('glacier_assets_cached', TRUE, time() + 604800, '/');
  }
}

/**
 * Implements template_process_html().
 */
function critical_path_css_process_html(&$vars) {
  // Only on first page load (nothing cached, cookie not set)
  // we inline the critical path CSS and load the rest of the
  // CSS files via loadCSS custom JS function
  if (_critical_path_css_is_active() && (!isset($_COOKIE['critical_path_css_cached']) || $_COOKIE['glacier_assets_cached'] == FALSE)) {
    // More info about loadCSS https://github.com/filamentgroup/loadCSS
    $script = 'function loadCSS(e,t,n){"use strict";var i=window.document.createElement("link");var o=t||window.document.getElementsByTagName("script")[0];i.rel="stylesheet";i.href=e;i.media="only x";o.parentNode.insertBefore(i,o);setTimeout(function(){i.media=n||"all"})}';

    // Find all paths of the cached stylesheets
    preg_match_all('#href="(.+?)"#', $vars['styles'], $css);
    // Add a loadCSS function for every stylesheet
    foreach ($css[1] as $file) {
      $script .= 'loadCSS("' . $file . '");';
    }
    // Load critical path CSS
    $critical_path_css = file_get_contents(drupal_get_path('theme', 'spattstrasse') . '/css/critical.min.css');
    // Remove <link> tags from styles
    $vars['styles'] = preg_replace('#\<link(.+?)\/\>#', '', $vars['styles']);
    // Add the inlined critical path CSS code to the styles variable
    $vars['styles'] = str_replace('</style>', $critical_path_css . '</style>', $vars['styles']);
    // Add the loadCSS code to the scripts variable
    $vars['scripts'] .= '<script>' . $script . '</script>';
  }
}

function _critical_path_css_is_active() {
  return (function_exists('path_is_admin') ? !path_is_admin(current_path()) : TRUE) && variable_get('preprocess_css');
}